### ISSUE TITLE
Individual doctor data sheet Error

### ISSUE THREAD

**Issue by surajTechlift** [techlift-tech/erpnext_oralcare#182]
[ERROR] 2019-12-16 14:57:52,277 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: startswith first arg must be str or a tuple of str, not bytes
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 511, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 201, in run
    result = generate_report_result(report, filters, user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 76, in generate_report_result
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/frappe/frappe-bench/apps/erpnext_oralcare/erpnext_oralcare/erpnext_oralcare/report/individual_doctor_data_sheet/individual_doctor_data_sheet.py", line 75, in execute
    company_percent = (company_share/amount)*100
ZeroDivisionError: float division by zero

**Comment by surajTechlift** [comment]
@palashjhabak  have pushed report with docstatus=1, have a look

**Comment by surajTechlift** [comment]
new report is ready with fix
